name: Deploy to Production

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.node-version'
    - name: Install
      run: yarn install
    - name: Build
      run: yarn build
    - name: Deploy to Production
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
        projectId: ng-japan
        target: app
        channelId: live